disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "üõ†Ô∏è JoelMathewC"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Joel Mathew Cherian"
  email = "joelmathewcherian@gmail.com"
  image = "profile.jpg"
  imageQuality = 96
  headline = "Developer ‚óÜ Engineer ‚óÜ Researcher"
  # bio = "A little bit about you"
  links = [
    { email = "mailto:joelmathewcherian@gmail.com" },
    { github = "https://github.com/JoelMathewC" },
    { linkedin = "https://www.linkedin.com/in/joelmathewc/" },
    { orcid = "https://orcid.org/0009-0006-8291-4229" },
  ]
