baseURL = 'https://joelmathewc.github.io/'
languageCode = 'en-us'
title = 'ğŸ› ï¸ JoelMathewC'
theme = 'blowfish'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  series = "series"
